openapi: 3.0.0
info:
  title: Cloudability API
  version: "1"
servers:
- url: https://virtserver.swaggerhub.com/lantrix/Cloudability/1
  description: SwaggerHub API Auto Mocking
- url: https://app.cloudability.com/api/1
  description: Production API
security:
- ApiKeyAuth: []
paths:
  /account_groups:
    get:
      description: List account groups
      responses:
        "200":
          description: Successful response
components:
  schemas: {}
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      name: auth_token
      in: query
