openapi: 3.0.0
info:
  title: Cloudability API
  version: "1"
servers:
- url: https://virtserver.swaggerhub.com/lantrix/Cloudability/1
  description: SwaggerHub API Auto Mocking
- url: https://app.cloudability.com/api/1
- url: https://api.cloudability.com/v3
security:
- BasicAuth: []
paths: {}
components:
  schemas:
    V3:
      type: object
      properties:
        id:
          type: integer
          format: int64
    V1:
      type: object
      properties:
        id:
          type: integer
          format: int64
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
